package com.aakruth.model;
// Generated Apr 16, 2017 12:21:33 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * BillTbl generated by hbm2java
 */
@Entity
@Table(name = "bill_tbl", catalog = "aakruthdb")
public class BillTbl implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer billId;
	@JsonView(DataTablesOutput.View.class)
	private Dealer dealer;
	@JsonView(DataTablesOutput.View.class)
	private UsrTbl usrTbl;
	private Date strdte;
	private char sta;
	private Date enddte;
	@JsonView(DataTablesOutput.View.class)
	private String poNum;
	@JsonView(DataTablesOutput.View.class)
	private Date entryDte;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal tax;
	@JsonIgnore
	private Set<SalTbl> salTbls = new HashSet<SalTbl>(0);

	@Override
	public String toString() {
		return "BillTbl [billId=" + billId + ", dealer=" + dealer + ", usrTbl=" + usrTbl + ", strdte=" + strdte
				+ ", sta=" + sta + ", enddte=" + enddte + ", poNum=" + poNum + ", entryDte=" + entryDte + ", tax=" + tax
				+ "]";
	}

	public BillTbl() {
	}

	public BillTbl(Dealer dealer, UsrTbl usrTbl, Date strdte, char sta, Date enddte) {
		this.dealer = dealer;
		this.usrTbl = usrTbl;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
	}

	public BillTbl(Dealer dealer, UsrTbl usrTbl, Date strdte, char sta, Date enddte, String poNum, Date entryDte,
			BigDecimal tax, Set<SalTbl> salTbls) {
		this.dealer = dealer;
		this.usrTbl = usrTbl;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
		this.poNum = poNum;
		this.entryDte = entryDte;
		this.tax = tax;
		this.salTbls = salTbls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BILL_ID", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLI_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID", nullable = false)
	public UsrTbl getUsrTbl() {
		return this.usrTbl;
	}

	public void setUsrTbl(UsrTbl usrTbl) {
		this.usrTbl = usrTbl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "po_num", length = 45)
	public String getPoNum() {
		return this.poNum;
	}

	public void setPoNum(String poNum) {
		this.poNum = poNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_dte", length = 10)
	public Date getEntryDte() {
		return this.entryDte;
	}

	public void setEntryDte(Date entryDte) {
		this.entryDte = entryDte;
	}

	@Column(name = "tax", precision = 10)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billTbl")
	public Set<SalTbl> getSalTbls() {
		return this.salTbls;
	}

	public void setSalTbls(Set<SalTbl> salTbls) {
		this.salTbls = salTbls;
	}

}
