package com.aakruth.model;
// Generated Apr 16, 2017 12:21:33 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * PrdTbl generated by hbm2java
 */
@Entity
@Table(name = "prd_tbl", catalog = "aakruthdb")
public class PrdTbl implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer prdId;
	@JsonView(DataTablesOutput.View.class)
	private Dealer dealer;
	@JsonView(DataTablesOutput.View.class)
	private String prdnme;
	@JsonView(DataTablesOutput.View.class)
	private String typ;
	@JsonView(DataTablesOutput.View.class)
	private Date strdte;
	@JsonView(DataTablesOutput.View.class)
	private Date enddte;
	@JsonView(DataTablesOutput.View.class)
	private char sta;
	@JsonView(DataTablesOutput.View.class)
	private short amc;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal amt;
	@JsonIgnore
	private Set<SalTbl> salTbls = new HashSet<SalTbl>(0);
	@JsonIgnore
	private Set<PurTbl> purTbls = new HashSet<PurTbl>(0);

	public PrdTbl() {
	}
	@Override
	public String toString() {
		return "PrdTbl [prdId=" + prdId + ", dealer=" + dealer + ", prdnme=" + prdnme + ", typ=" + typ + ", strdte="
				+ strdte + ", enddte=" + enddte + ", sta=" + sta + ", amc=" + amc + ", amt=" + amt + "]";
	}
	public PrdTbl(Dealer dealer, String prdnme, String typ, Date strdte, Date enddte, char sta, short amc,
			BigDecimal amt) {
		this.dealer = dealer;
		this.prdnme = prdnme;
		this.typ = typ;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.amc = amc;
		this.amt = amt;
	}

	public PrdTbl(Dealer dealer, String prdnme, String typ, Date strdte, Date enddte, char sta, short amc,
			BigDecimal amt, Set<SalTbl> salTbls, Set<PurTbl> purTbls) {
		this.dealer = dealer;
		this.prdnme = prdnme;
		this.typ = typ;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.amc = amc;
		this.amt = amt;
		this.salTbls = salTbls;
		this.purTbls = purTbls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRD_ID", unique = true, nullable = false)
	public Integer getPrdId() {
		return this.prdId;
	}

	public void setPrdId(Integer prdId) {
		this.prdId = prdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLD_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@Column(name = "PRDNME", nullable = false, length = 45)
	public String getPrdnme() {
		return this.prdnme;
	}

	public void setPrdnme(String prdnme) {
		this.prdnme = prdnme;
	}

	@Column(name = "TYP", nullable = false, length = 45)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "AMC", nullable = false, precision = 3, scale = 0)
	public short getAmc() {
		return this.amc;
	}

	public void setAmc(short amc) {
		this.amc = amc;
	}

	@Column(name = "AMT", nullable = false, precision = 10)
	public BigDecimal getAmt() {
		return this.amt;
	}

	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prdTbl")
	public Set<SalTbl> getSalTbls() {
		return this.salTbls;
	}

	public void setSalTbls(Set<SalTbl> salTbls) {
		this.salTbls = salTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prdTbl")
	public Set<PurTbl> getPurTbls() {
		return this.purTbls;
	}

	public void setPurTbls(Set<PurTbl> purTbls) {
		this.purTbls = purTbls;
	}

}
