package com.aakruth.model;
// Generated Apr 16, 2017 12:21:33 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonView;

/**
 * RoleTbl generated by hbm2java
 */
@Entity
@Table(name = "role_tbl", catalog = "aakruthdb")
public class RoleTbl implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer roleId;
	@JsonView(DataTablesOutput.View.class)
	private UsrTbl usrTbl;
	@JsonView(DataTablesOutput.View.class)
	private String role;

	@Override
	public String toString() {
		return "RoleTbl [roleId=" + roleId + ", usrTbl=" + usrTbl + ", role=" + role + "]";
	}

	public RoleTbl() {
	}

	public RoleTbl(UsrTbl usrTbl, String role) {
		this.usrTbl = usrTbl;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID", nullable = false)
	public UsrTbl getUsrTbl() {
		return this.usrTbl;
	}

	public void setUsrTbl(UsrTbl usrTbl) {
		this.usrTbl = usrTbl;
	}

	@Column(name = "ROLE", nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
