package com.aakruth.model;
// Generated Apr 16, 2017 12:21:33 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * UsrTbl generated by hbm2java
 */
@Entity
@Table(name = "usr_tbl", catalog = "aakruthdb")
public class UsrTbl implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer usrId;
	@JsonView(DataTablesOutput.View.class)
	private String usrnme;
	@JsonView(DataTablesOutput.View.class)
	private String phnnbr;
	@JsonView(DataTablesOutput.View.class)
	private String email;
	@JsonView(DataTablesOutput.View.class)
	private String adr;
	private Date strdte;
	private Date enddte;
	private char sta;
	private String pswd;
	@JsonIgnore
	private Set<BillTbl> billTbls = new HashSet<BillTbl>(0);
	@JsonIgnore
	private Set<PurTbl> purTbls = new HashSet<PurTbl>(0);
	@JsonIgnore
	private Set<RoleTbl> roleTbls = new HashSet<RoleTbl>(0);

	@Override
	public String toString() {
		return "UsrTbl [usrId=" + usrId + ", usrnme=" + usrnme + ", phnnbr=" + phnnbr + ", email=" + email + ", adr="
				+ adr + ", strdte=" + strdte + ", enddte=" + enddte + ", sta=" + sta + "]";
	}

	public UsrTbl() {
	}

	public UsrTbl(String usrnme, String phnnbr, String email, String adr, Date strdte, Date enddte, char sta,
			String pswd) {
		this.usrnme = usrnme;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.pswd = pswd;
	}

	public UsrTbl(String usrnme, String phnnbr, String email, String adr, Date strdte, Date enddte, char sta,
			String pswd, Set<BillTbl> billTbls, Set<PurTbl> purTbls, Set<RoleTbl> roleTbls) {
		this.usrnme = usrnme;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.pswd = pswd;
		this.billTbls = billTbls;
		this.purTbls = purTbls;
		this.roleTbls = roleTbls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USR_ID", unique = true, nullable = false)
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@Column(name = "USRNME", nullable = false, length = 45)
	public String getUsrnme() {
		return this.usrnme;
	}

	public void setUsrnme(String usrnme) {
		this.usrnme = usrnme;
	}

	@Column(name = "PHNNBR", nullable = false, length = 10)
	public String getPhnnbr() {
		return this.phnnbr;
	}

	public void setPhnnbr(String phnnbr) {
		this.phnnbr = phnnbr;
	}

	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADR", nullable = false, length = 45)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "PSWD", nullable = false, length = 45)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrTbl")
	public Set<BillTbl> getBillTbls() {
		return this.billTbls;
	}

	public void setBillTbls(Set<BillTbl> billTbls) {
		this.billTbls = billTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrTbl")
	public Set<PurTbl> getPurTbls() {
		return this.purTbls;
	}

	public void setPurTbls(Set<PurTbl> purTbls) {
		this.purTbls = purTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrTbl")
	public Set<RoleTbl> getRoleTbls() {
		return this.roleTbls;
	}

	public void setRoleTbls(Set<RoleTbl> roleTbls) {
		this.roleTbls = roleTbls;
	}

}
